language: node_js
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test

before_deploy:
  - npm run build-storybook
  - npm pack

# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: storybook-static
    on:
      branch: master
  - provider: npm
    email: $NPM_EMAIL
    api_key: $NPM_TOKEN
    skip_cleanup: true
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "govuk-react-*.tgz"
    skip_cleanup: true
    on:
      tags: true
