language: node_js
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
  - yarn bootstrap
  - yarn build
  - npm install -g codecov
script:
#  - npm run build # npm install already runs a build via prepare
  - npm test
  - codecov
  - npm run build:dist # the dist build is only used to track bundle sizes
  - npm run bundlesize
before_deploy:
  - npm run build-storybook
deploy:
  - provider: pages # https://docs.travis-ci.com/user/deployment/pages/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: storybook-static
    on:
      branch: master
