language: node_js
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
  - yarn bootstrap
  - yarn build
  - npm install -g codecov
script:
#  - npm run build # npm install already runs a build via prepare
  - npm test
  - codecov
  - npm run build:dist # the dist build is only used to track bundle sizes
  - npm run bundlesize
before_deploy:
  - npm run build-storybook
  - npm run pack
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
deploy:
  - provider: pages # https://docs.travis-ci.com/user/deployment/pages/
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
    keep-history: true
    local-dir: storybook-static
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: lerna exec --no-private --bail=false -- "can-npm-publish && npm publish"
    on:
      tags: true
  - provider: releases
    api_key: $GITHUB_TOKEN
    file_glob: true
    file: "{components,packages}/*/govuk-react-*.tgz"
    skip_cleanup: true
    on:
      tags: true
