name: Chromatic
on: push
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required by Chromatic

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '10.x'

      - run: yarn
      - run: yarn build:storybook

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: 06clhw0peccl
          storybookBuildDir: packages/storybook/storybook-static
  