name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '10.x'

      - run: yarn
      - run: npm install -g codecov
      - run: yarn build:sync
      - run: yarn docs
      - run: yarn test
      - run: codecov
      - run: yarn build:dist # the dist build is only used to track bundle size delta
      - run: yarn bundlesize
  
  automerge:
    needs: build-lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

