name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required by Chromatic

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - run: yarn
      - run: npm install -g codecov
      - run: yarn build:sync
      - run: yarn test
      - run: codecov
      - run: yarn build:dist # the dist build is only used to track bundle size delta
      - run: yarn bundlesize

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          storybookBuildDir: packages/storybook/storybook-static
  
  automerge:
    needs: build-lint-test
    runs-on: ubuntu-latest
    steps:
      - uses: fastify/github-action-merge-dependabot@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

