name: GitHub Pages
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm

      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: "${{ steps.nvm.outputs.NVMRC }}"

      - run: yarn
      - run: yarn build:storybook

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: packages/storybook/storybook-static # The folder the action should deploy.
